"""Built-in skill: build a zero-dependency Rust HTTP server.

Uses only Rust's standard library (std::net::TcpListener) — no crates.io
access required.  A pre-committed Cargo.lock lets ``cargo build --offline``
succeed without any network calls, which means this works even when the
crates.io registry index has not been fetched yet.

Typical agent workflow after calling this skill:

    1. build_std_rust_http_server(build_dir="/tmp/rust-srv", port=8080)
       -> returns {"built": true, "binary_path": "...", ...}
    2. execute_background_service("/tmp/rust-srv/target/release/std-http-server 8080")
    3. expose_local_http_service(port=8080)
"""
from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

from _skill import skill  # _skill is injected into sys.path by the skills server

# ---------------------------------------------------------------------------
# Rust source — std::net only, zero external crates
# ---------------------------------------------------------------------------

_MAIN_RS = r"""use std::io::{Read, Write};
use std::net::TcpListener;

fn main() {
    let port: u16 = std::env::args()
        .nth(1)
        .and_then(|p| p.parse().ok())
        .unwrap_or(8080);

    let listener = TcpListener::bind(("0.0.0.0", port))
        .unwrap_or_else(|e| panic!("Failed to bind to 0.0.0.0:{port}: {e}"));

    eprintln!("Rust std-only HTTP server listening on 0.0.0.0:{port}");

    for stream in listener.incoming() {
        if let Ok(mut stream) = stream {
            let mut buf = [0u8; 4096];
            let _ = stream.read(&mut buf);
            let body = format!("Hello from Rust (port {port})!\n");
            let response = format!(
                "HTTP/1.1 200 OK\r\nContent-Length: {}\r\n\
                 Content-Type: text/plain\r\nConnection: close\r\n\r\n{}",
                body.len(),
                body
            );
            let _ = stream.write_all(response.as_bytes());
        }
    }
}
"""

# ---------------------------------------------------------------------------
# Project manifest — pure-std, no external crates
# ---------------------------------------------------------------------------

_CARGO_TOML = """\
[package]
name = "std-http-server"
version = "0.1.0"
edition = "2021"

# No external crates — only the Rust standard library is used.
# Omitting the [dependencies] table entirely tells cargo there are none.
# This compiles without any network access to crates.io.
"""

# ---------------------------------------------------------------------------
# Pre-generated Cargo.lock for a zero-dependency binary.
#
# Cargo.lock version 3 (Rust 1.78+).  Because there are no external crates,
# this file contains only the root package entry.  Committing it lets
# ``cargo build --offline --frozen`` succeed without fetching the registry
# index, so the build works even in an air-gapped container.
# ---------------------------------------------------------------------------

_CARGO_LOCK = """\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "std-http-server"
version = "0.1.0"
"""


# ---------------------------------------------------------------------------
# Skill
# ---------------------------------------------------------------------------


@skill(
    name="build_std_rust_http_server",
    description=(
        "Build a minimal Rust HTTP server using ONLY std::net — no external "
        "crates, no crates.io access required.  Works with the pre-installed "
        "Rust toolchain; the build is fully offline. "
        "Returns JSON with: built (bool), binary_path (str|null), exit_code (int), "
        "stderr (str), launch_command (str). "
        "After a successful build: call execute_background_service(launch_command), "
        "then call expose_local_http_service(port=<port>) to get a browser URL."
    ),
)
def build_std_rust_http_server(
    build_dir: str = "/tmp/std-rust-server",
    port: int = 8080,
) -> str:
    """Build a zero-dependency Rust HTTP server and return JSON evidence."""
    project_dir = Path(build_dir).expanduser().resolve()
    src_dir = project_dir / "src"
    src_dir.mkdir(parents=True, exist_ok=True)

    # Write project files
    (project_dir / "Cargo.toml").write_text(_CARGO_TOML, encoding="utf-8")
    (project_dir / "Cargo.lock").write_text(_CARGO_LOCK, encoding="utf-8")
    (src_dir / "main.rs").write_text(_MAIN_RS, encoding="utf-8")

    # Build offline (Cargo.lock is pre-committed; zero external deps = no registry needed)
    result = subprocess.run(
        ["cargo", "build", "--release", "--offline", "--frozen"],
        cwd=str(project_dir),
        capture_output=True,
        text=True,
        timeout=300,
        env={**os.environ, "CARGO_TERM_COLOR": "never"},
    )

    binary_name = "std-http-server" + (".exe" if os.name == "nt" else "")
    binary_path = project_dir / "target" / "release" / binary_name

    return json.dumps(
        {
            "built": result.returncode == 0,
            "binary_path": str(binary_path) if binary_path.exists() else None,
            "binary_exists": binary_path.exists(),
            "exit_code": result.returncode,
            "stdout": result.stdout[-2000:],
            "stderr": result.stderr[-2000:],
            "project_dir": str(project_dir),
            "launch_command": f"{binary_path} {port}",
            "next_steps": [
                f"execute_background_service('{binary_path} {port}')",
                f"expose_local_http_service(port={port})",
            ],
        },
        indent=2,
    )
